# infra/compose.base.yml

services:
  backend:
    # fără container_name -> Docker Compose va crea nume unice de genul: proiect_backend_1
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: appdb
    ports:
      - "3000:3000"   # opțional pentru curl direct în backend

  web:
    depends_on:
      backend:
        condition: service_started   # în dev (fără healthcheck complex)
    ports:
      - "8081:80"     # host:container
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      # DEV default: scrape backend:3000
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdata:
  prom_data:
  grafana_data:

