# infra/docker-compose.dev.yml
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

  web:
    image: nginx:alpine
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      backend:
        condition: service_started

  prometheus:
    volumes:
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro