global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape the Node.js backend directly on the Compose network
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:3000"]
